import northcoat from "../images/northcoat.png";
export const Trending = [
  {
    id: "1",
    label: "The North Coat",
    image: <img src={northcoat} alt="The North Coat" />,
    images: [
      { url: northcoat },
      { url: northcoat },
      { url: northcoat },
      { url: northcoat },
      { url: northcoat },
    ],
    currentPrice: "$ 260",
    originalPrice: "$ 360",
    ratings: 65,
    discountRate: "40%",
    category: "men shirt",
    freeDelivery: true,
    stock: 100,
    description:
      "PlayStation 5 Controller Skin High quality vinyl with air channel adhesive for easy bubble free install & mess free removal Pressure sensitive.",
  },
  {
    id: "2",
    label: "The North Coat",
    image: <img src={northcoat} alt="The North Coat" />,
    images: [
      { url: northcoat },
      { url: northcoat },
      { url: northcoat },
      { url: northcoat },
      { url: northcoat },
    ],
    currentPrice: "$ 260",
    originalPrice: "$ 360",
    ratings: 65,
    discountRate: "40%",
    category: "men shirt",
    freeDelivery: true,
    inStock: true,
    stock: 0,
    description:
      "PlayStation 5 Controller Skin High quality vinyl with air channel adhesive for easy bubble free install & mess free removal Pressure sensitive.",
  },
  {
    id: "3",
    label: "The North Coat",
    image: <img src={northcoat} alt="The North Coat" />,
    images: [
      { url: northcoat },
      { url: northcoat },
      { url: northcoat },
      { url: northcoat },
      { url: northcoat },
    ],
    currentPrice: "$ 260",
    originalPrice: "$ 360",
    ratings: 65,
    discountRate: "40%",
    category: "men shirt",
    freeDelivery: true,
    inStock: true,
    stock: 100,

    description:
      "PlayStation 5 Controller Skin High quality vinyl with air channel adhesive for easy bubble free install & mess free removal Pressure sensitive.",
  },
  {
    id: "4",
    label: "The North Coat",
    image: <img src={northcoat} alt="The North Coat" />,
    images: [
      { url: northcoat },
      { url: northcoat },
      { url: northcoat },
      { url: northcoat },
      { url: northcoat },
    ],
    currentPrice: "$ 260",
    originalPrice: "$ 360",
    ratings: 65,
    discountRate: "40%",
    category: "men shirt",
    freeDelivery: true,
    stock: 100,
    description:
      "PlayStation 5 Controller Skin High quality vinyl with air channel adhesive for easy bubble free install & mess free removal Pressure sensitive.",
  },
  {
    id: "5",
    label: "The North Coat",
    image: <img src={northcoat} alt="The North Coat" />,
    images: [
      { url: northcoat },
      { url: northcoat },
      { url: northcoat },
      { url: northcoat },
      { url: northcoat },
    ],
    currentPrice: "$ 260",
    originalPrice: "$ 360",
    ratings: 65,
    discountRate: "40%",
    category: "men shirt",
    freeDelivery: true,
    stock: 100,
    description:
      "PlayStation 5 Controller Skin High quality vinyl with air channel adhesive for easy bubble free install & mess free removal Pressure sensitive.",
  },
  {
    id: "6",
    label: "The North Coat",
    image: <img src={northcoat} alt="The North Coat" />,
    images: [
      { url: northcoat },
      { url: northcoat },
      { url: northcoat },
      { url: northcoat },
      { url: northcoat },
    ],
    currentPrice: "$ 260",
    originalPrice: "$ 360",
    ratings: 65,
    discountRate: "40%",
    category: "men shirt",
    freeDelivery: true,
    inStock: true,
    stock: 0,
    description:
      "PlayStation 5 Controller Skin High quality vinyl with air channel adhesive for easy bubble free install & mess free removal Pressure sensitive.",
  },
  {
    id: "7",
    label: "The North Coat",
    image: <img src={northcoat} alt="The North Coat" />,
    images: [
      { url: northcoat },
      { url: northcoat },
      { url: northcoat },
      { url: northcoat },
      { url: northcoat },
    ],
    currentPrice: "$ 260",
    originalPrice: "$ 360",
    ratings: 65,
    discountRate: "40%",
    category: "men shirt",
    freeDelivery: true,
    inStock: true,
    stock: 100,

    description:
      "PlayStation 5 Controller Skin High quality vinyl with air channel adhesive for easy bubble free install & mess free removal Pressure sensitive.",
  },
  {
    id: "8",
    label: "The North Coat",
    image: <img src={northcoat} alt="The North Coat" />,
    images: [
      { url: northcoat },
      { url: northcoat },
      { url: northcoat },
      { url: northcoat },
      { url: northcoat },
    ],
    currentPrice: "$ 260",
    originalPrice: "$ 360",
    ratings: 65,
    discountRate: "40%",
    category: "men shirt",
    freeDelivery: true,
    stock: 100,
    description:
      "PlayStation 5 Controller Skin High quality vinyl with air channel adhesive for easy bubble free install & mess free removal Pressure sensitive.",
  },
];
